# Generated by Django 5.1.6 on 2025-02-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rangobom_main', '0002_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
