# Generated by Django 5.1.6 on 2025-02-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangobom_main', '0003_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
