# Generated by Django 5.1.6 on 2025-02-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangobom_main', '0004_alter_company_latitude_alter_company_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
