# Generated by Django 5.1.6 on 2025-02-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangobom_main', '0005_company_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='company',
            name='profile_image_url',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
